name: Build

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        build-configuration: [Debug, RelWithDebInfo, Release]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - name: Install Dependencies
        run: sudo apt update &&
             wget https://apt.llvm.org/llvm.sh &&
             sudo apt install build-essential &&
             sudo chmod u+x llvm.sh &&
             sudo sh -c "yes | ./llvm.sh 18" &&
             sudo apt update && sudo apt install -y ninja-build clang vulkan-tools libvulkan-dev vulkan-validationlayers-dev spirv-tools libx11-dev libx11-xcb-dev
             libwayland-bin libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev pkg-config libwayland-dev libxkbcommon-dev libglvnd-dev wayland-protocols

      - name: Generate Cache
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: (cd Vortex-Engine/vendor/shaderc && ./utils/git-sync-deps) && 
             cmake -B build -G Ninja -S . -DCMAKE_BUILD_TYPE=${{ matrix.build-configuration }} -DCMAKE_CXX_COMPILER=clang++-18 &&
             chmod +x ./gen-wayland-headers.sh && ./gen-wayland-headers.sh 
      
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: cmake --build build
