name: Build

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        build-configuration: [Debug, Release, Dist]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - name: Build
        uses: threeat/cmake-action@main
        with:
          source-dir: .
          build-dir: build
          generator: Ninja
          c-compiler: clang
          cxx-compiler: clang++
          run-build: true
          args: -DCMAKE_BUILD_TYPE=${{ matrix.build-configuration }}
